# Generated by Django 4.0.2 on 2022-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='events3.jfif', upload_to='post_images'),
        ),
    ]
