# Generated by Django 4.0.2 on 2022-06-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='ngong.jpg', null=True, upload_to='media'),
        ),
    ]
